openapi: 3.0.3
info:
  title: バックエンド側API仕様
  description: バックエンド側API仕様
  version: 1.0.0
servers:
  - url: 'https://ynufes-mypage.shion.pro'
    variables:
      basePath:
        default: '/api/v1'
paths:
  /auth/line/state:
    get:
      summary: LINEログインのstateを取得する
      description: このリクエストで受け取ったstateを用いてLINEログイン用のURLを動的に生成し、誘導させる
      responses:
        '200':
          description: 正常に取得できた
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
                example: '10693189634815248950'
        '500':
          description: サーバーエラー
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
                description: エラーメッセージ
                example: 'エラーメッセージ'
  /user/info:
    get:
      summary: ユーザー情報を取得する
      description: ユーザー情報を取得、または認証情報の有効性を確認
      parameters:
        - name: Authorization
          in: header
          description: Cookieに保存されいる認証情報。
          required: true
          example: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOi0yODc3NDMxOTIzLCJqdGkiOiJlNnhxMDRraTUyd3ciLCJpYXQiOjE2NzE4MDkzMzMsImlzcyI6InludWZlcy1teXBhZ2Uuc2hpb24ucHJvIn0.YiK1KK7kGSt6rAlgprXiJ4PiKxPCeluwYarV6JL6l2s'
          schema:
            type: string
      responses:
        '200':
          description: 正常なレスポンス
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserInfo'
        '401':
          description: 認証エラー(→ログインページへ)
        '500':
          description: サーバーエラー
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
                description: エラーメッセージ
                example: 'エラーメッセージ'
  /user/info/update:
    post:
      summary: ユーザー情報を更新する
      description: ユーザー情報を更新する
      parameters:
        - name: Authorization
          in: header
          description: Cookieに保存されいる認証情報。
          required: true
          example: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOi0yODc3NDMxOTIzLCJqdGkiOiJlNnhxMDRraTUyd3ciLCJpYXQiOjE2NzE4MDkzMzMsImlzcyI6InludWZlcy1teXBhZ2Uuc2hpb24ucHJvIn0.YiK1KK7kGSt6rAlgprXiJ4PiKxPCeluwYarV6JL6l2s'
          schema:
            type: string
      responses:
        '200':
          description: 正常なレスポンス
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserInfo'
        '401':
          description: 認証エラー(→ログインページへ)
        '500':
          description: サーバーエラー
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
                description: エラーメッセージ
                example: 'エラーメッセージ'
components:
  schemas:
    UserInfo:
      type: object
      properties:
        name_first:
          type: integer
          description: 名前(名)
          example: '詩恩'
        name_last:
          type: string
          description: 名前(姓)
          example: '市川'
        type:
          type: integer
          description: ユーザー属性。現時点では0のみ。(0:一般ユーザー)
          example: 0
        profile_icon_url:
          type: string
          description: プロフィール画像のURL, Lineアイコン画像と同一。
          example: 'https://profile.line-scdn.net/0h73ggAo9NaBxKHn0UROAWYzpOa3ZpbzEONnF0LXpNMS0jLXxDZXhwLn9LNiVwKXtLYnsjKHwdMS9GDR96VEiUKE0uNitzKChJY3Ei_A'
        status:
          type: integer
          description: ユーザー登録状態。基本情報未登録の場合は0, 登録済みの場合は1。(0:未登録, 1:登録済み)
          example: 0